//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PCIBusiness.IkajoService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PtCardBinding", Namespace="urn:PtCard")]
    public partial class PtCardService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authOperationCompleted;
        
        private System.Threading.SendOrPostCallback saleOperationCompleted;
        
        private System.Threading.SendOrPostCallback captureOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback authRebillOperationCompleted;
        
        private System.Threading.SendOrPostCallback rebillOperationCompleted;
        
        private System.Threading.SendOrPostCallback statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback scheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback descheduleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PtCardService() {
            this.Url = global::PCIBusiness.Properties.Settings.Default.PCIBusiness_IkajoService_PtCardService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authCompletedEventHandler authCompleted;
        
        /// <remarks/>
        public event saleCompletedEventHandler saleCompleted;
        
        /// <remarks/>
        public event captureCompletedEventHandler captureCompleted;
        
        /// <remarks/>
        public event cancelCompletedEventHandler cancelCompleted;
        
        /// <remarks/>
        public event authRebillCompletedEventHandler authRebillCompleted;
        
        /// <remarks/>
        public event rebillCompletedEventHandler rebillCompleted;
        
        /// <remarks/>
        public event statusCompletedEventHandler statusCompleted;
        
        /// <remarks/>
        public event scheduleCompletedEventHandler scheduleCompleted;
        
        /// <remarks/>
        public event descheduleCompletedEventHandler descheduleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("saleReturn")]
        public SaleResult auth(SaleRequest @params) {
            object[] results = this.Invoke("auth", new object[] {
                        @params});
            return ((SaleResult)(results[0]));
        }
        
        /// <remarks/>
        public void authAsync(SaleRequest @params) {
            this.authAsync(@params, null);
        }
        
        /// <remarks/>
        public void authAsync(SaleRequest @params, object userState) {
            if ((this.authOperationCompleted == null)) {
                this.authOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthOperationCompleted);
            }
            this.InvokeAsync("auth", new object[] {
                        @params}, this.authOperationCompleted, userState);
        }
        
        private void OnauthOperationCompleted(object arg) {
            if ((this.authCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authCompleted(this, new authCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("saleReturn")]
        public SaleResult sale(SaleRequest @params) {
            object[] results = this.Invoke("sale", new object[] {
                        @params});
            return ((SaleResult)(results[0]));
        }
        
        /// <remarks/>
        public void saleAsync(SaleRequest @params) {
            this.saleAsync(@params, null);
        }
        
        /// <remarks/>
        public void saleAsync(SaleRequest @params, object userState) {
            if ((this.saleOperationCompleted == null)) {
                this.saleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaleOperationCompleted);
            }
            this.InvokeAsync("sale", new object[] {
                        @params}, this.saleOperationCompleted, userState);
        }
        
        private void OnsaleOperationCompleted(object arg) {
            if ((this.saleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saleCompleted(this, new saleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("captureReturn")]
        public CaptureResult capture(CaptureRequest @params) {
            object[] results = this.Invoke("capture", new object[] {
                        @params});
            return ((CaptureResult)(results[0]));
        }
        
        /// <remarks/>
        public void captureAsync(CaptureRequest @params) {
            this.captureAsync(@params, null);
        }
        
        /// <remarks/>
        public void captureAsync(CaptureRequest @params, object userState) {
            if ((this.captureOperationCompleted == null)) {
                this.captureOperationCompleted = new System.Threading.SendOrPostCallback(this.OncaptureOperationCompleted);
            }
            this.InvokeAsync("capture", new object[] {
                        @params}, this.captureOperationCompleted, userState);
        }
        
        private void OncaptureOperationCompleted(object arg) {
            if ((this.captureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.captureCompleted(this, new captureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("cancelReturn")]
        public CancelResult cancel(CancelRequest @params) {
            object[] results = this.Invoke("cancel", new object[] {
                        @params});
            return ((CancelResult)(results[0]));
        }
        
        /// <remarks/>
        public void cancelAsync(CancelRequest @params) {
            this.cancelAsync(@params, null);
        }
        
        /// <remarks/>
        public void cancelAsync(CancelRequest @params, object userState) {
            if ((this.cancelOperationCompleted == null)) {
                this.cancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelOperationCompleted);
            }
            this.InvokeAsync("cancel", new object[] {
                        @params}, this.cancelOperationCompleted, userState);
        }
        
        private void OncancelOperationCompleted(object arg) {
            if ((this.cancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelCompleted(this, new cancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("rebillReturn")]
        public RebillResult authRebill(RebillRequest @params) {
            object[] results = this.Invoke("authRebill", new object[] {
                        @params});
            return ((RebillResult)(results[0]));
        }
        
        /// <remarks/>
        public void authRebillAsync(RebillRequest @params) {
            this.authRebillAsync(@params, null);
        }
        
        /// <remarks/>
        public void authRebillAsync(RebillRequest @params, object userState) {
            if ((this.authRebillOperationCompleted == null)) {
                this.authRebillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthRebillOperationCompleted);
            }
            this.InvokeAsync("authRebill", new object[] {
                        @params}, this.authRebillOperationCompleted, userState);
        }
        
        private void OnauthRebillOperationCompleted(object arg) {
            if ((this.authRebillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authRebillCompleted(this, new authRebillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("rebillReturn")]
        public RebillResult rebill(RebillRequest @params) {
            object[] results = this.Invoke("rebill", new object[] {
                        @params});
            return ((RebillResult)(results[0]));
        }
        
        /// <remarks/>
        public void rebillAsync(RebillRequest @params) {
            this.rebillAsync(@params, null);
        }
        
        /// <remarks/>
        public void rebillAsync(RebillRequest @params, object userState) {
            if ((this.rebillOperationCompleted == null)) {
                this.rebillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrebillOperationCompleted);
            }
            this.InvokeAsync("rebill", new object[] {
                        @params}, this.rebillOperationCompleted, userState);
        }
        
        private void OnrebillOperationCompleted(object arg) {
            if ((this.rebillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rebillCompleted(this, new rebillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("statusReturn")]
        public StatusResult status(StatusRequest @params) {
            object[] results = this.Invoke("status", new object[] {
                        @params});
            return ((StatusResult)(results[0]));
        }
        
        /// <remarks/>
        public void statusAsync(StatusRequest @params) {
            this.statusAsync(@params, null);
        }
        
        /// <remarks/>
        public void statusAsync(StatusRequest @params, object userState) {
            if ((this.statusOperationCompleted == null)) {
                this.statusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstatusOperationCompleted);
            }
            this.InvokeAsync("status", new object[] {
                        @params}, this.statusOperationCompleted, userState);
        }
        
        private void OnstatusOperationCompleted(object arg) {
            if ((this.statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.statusCompleted(this, new statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("scheduleReturn")]
        public ScheduleResult schedule(ScheduleRequest @params) {
            object[] results = this.Invoke("schedule", new object[] {
                        @params});
            return ((ScheduleResult)(results[0]));
        }
        
        /// <remarks/>
        public void scheduleAsync(ScheduleRequest @params) {
            this.scheduleAsync(@params, null);
        }
        
        /// <remarks/>
        public void scheduleAsync(ScheduleRequest @params, object userState) {
            if ((this.scheduleOperationCompleted == null)) {
                this.scheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnscheduleOperationCompleted);
            }
            this.InvokeAsync("schedule", new object[] {
                        @params}, this.scheduleOperationCompleted, userState);
        }
        
        private void OnscheduleOperationCompleted(object arg) {
            if ((this.scheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.scheduleCompleted(this, new scheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PtCardAction", RequestNamespace="urn:PtCard", ResponseNamespace="urn:PtCard")]
        [return: System.Xml.Serialization.SoapElementAttribute("descheduleReturn")]
        public DescheduleResult deschedule(DescheduleRequest @params) {
            object[] results = this.Invoke("deschedule", new object[] {
                        @params});
            return ((DescheduleResult)(results[0]));
        }
        
        /// <remarks/>
        public void descheduleAsync(DescheduleRequest @params) {
            this.descheduleAsync(@params, null);
        }
        
        /// <remarks/>
        public void descheduleAsync(DescheduleRequest @params, object userState) {
            if ((this.descheduleOperationCompleted == null)) {
                this.descheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescheduleOperationCompleted);
            }
            this.InvokeAsync("deschedule", new object[] {
                        @params}, this.descheduleOperationCompleted, userState);
        }
        
        private void OndescheduleOperationCompleted(object arg) {
            if ((this.descheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.descheduleCompleted(this, new descheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class SaleRequest {
        
        private string cardExpirationField;
        
        private string cardNumberField;
        
        private string cardTypeField;
        
        private string cardVerificationCodeField;
        
        private string customerAddressField;
        
        private string customerCityField;
        
        private string customerCountryField;
        
        private string customerEmailField;
        
        private string customerIPField;
        
        private string customerNameField;
        
        private string customerPhoneNumberField;
        
        private string customerStateField;
        
        private string customerZipCodeField;
        
        private string initRecurringField;
        
        private string merchantIDField;
        
        private string channelIDField;
        
        private string orderAmountField;
        
        private string orderCurrencyField;
        
        private string orderDescriptionField;
        
        private string orderReferenceField;
        
        private string returnUrlField;
        
        private string signatureField;
        
        /// <remarks/>
        public string cardExpiration {
            get {
                return this.cardExpirationField;
            }
            set {
                this.cardExpirationField = value;
            }
        }
        
        /// <remarks/>
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string cardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string cardVerificationCode {
            get {
                return this.cardVerificationCodeField;
            }
            set {
                this.cardVerificationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string customerAddress {
            get {
                return this.customerAddressField;
            }
            set {
                this.customerAddressField = value;
            }
        }
        
        /// <remarks/>
        public string customerCity {
            get {
                return this.customerCityField;
            }
            set {
                this.customerCityField = value;
            }
        }
        
        /// <remarks/>
        public string customerCountry {
            get {
                return this.customerCountryField;
            }
            set {
                this.customerCountryField = value;
            }
        }
        
        /// <remarks/>
        public string customerEmail {
            get {
                return this.customerEmailField;
            }
            set {
                this.customerEmailField = value;
            }
        }
        
        /// <remarks/>
        public string customerIP {
            get {
                return this.customerIPField;
            }
            set {
                this.customerIPField = value;
            }
        }
        
        /// <remarks/>
        public string customerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string customerPhoneNumber {
            get {
                return this.customerPhoneNumberField;
            }
            set {
                this.customerPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string customerState {
            get {
                return this.customerStateField;
            }
            set {
                this.customerStateField = value;
            }
        }
        
        /// <remarks/>
        public string customerZipCode {
            get {
                return this.customerZipCodeField;
            }
            set {
                this.customerZipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string initRecurring {
            get {
                return this.initRecurringField;
            }
            set {
                this.initRecurringField = value;
            }
        }
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string channelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderAmount {
            get {
                return this.orderAmountField;
            }
            set {
                this.orderAmountField = value;
            }
        }
        
        /// <remarks/>
        public string orderCurrency {
            get {
                return this.orderCurrencyField;
            }
            set {
                this.orderCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string orderDescription {
            get {
                return this.orderDescriptionField;
            }
            set {
                this.orderDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string returnUrl {
            get {
                return this.returnUrlField;
            }
            set {
                this.returnUrlField = value;
            }
        }
        
        /// <remarks/>
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class DescheduleResult {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string statusCodeField;
        
        private string transactionStatusField;
        
        private string transactionTypeField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class DescheduleRequest {
        
        private string merchantIDField;
        
        private string originalOrderReferenceField;
        
        private string recurringTokenField;
        
        private string signatureField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string originalOrderReference {
            get {
                return this.originalOrderReferenceField;
            }
            set {
                this.originalOrderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string recurringToken {
            get {
                return this.recurringTokenField;
            }
            set {
                this.recurringTokenField = value;
            }
        }
        
        /// <remarks/>
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class ScheduleResult {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string statusCodeField;
        
        private string transactionStatusField;
        
        private string transactionTypeField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class ScheduleRequest {
        
        private string merchantIDField;
        
        private string orderAmountField;
        
        private string orderDescriptionField;
        
        private string originalOrderReferenceField;
        
        private string recurringTokenField;
        
        private string scheduleCountField;
        
        private string scheduleDelayField;
        
        private string schedulePeriodField;
        
        private string signatureField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderAmount {
            get {
                return this.orderAmountField;
            }
            set {
                this.orderAmountField = value;
            }
        }
        
        /// <remarks/>
        public string orderDescription {
            get {
                return this.orderDescriptionField;
            }
            set {
                this.orderDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string originalOrderReference {
            get {
                return this.originalOrderReferenceField;
            }
            set {
                this.originalOrderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string recurringToken {
            get {
                return this.recurringTokenField;
            }
            set {
                this.recurringTokenField = value;
            }
        }
        
        /// <remarks/>
        public string scheduleCount {
            get {
                return this.scheduleCountField;
            }
            set {
                this.scheduleCountField = value;
            }
        }
        
        /// <remarks/>
        public string scheduleDelay {
            get {
                return this.scheduleDelayField;
            }
            set {
                this.scheduleDelayField = value;
            }
        }
        
        /// <remarks/>
        public string schedulePeriod {
            get {
                return this.schedulePeriodField;
            }
            set {
                this.schedulePeriodField = value;
            }
        }
        
        /// <remarks/>
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class StatusResult {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string orderStatusField;
        
        private string orderErrorField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string orderError {
            get {
                return this.orderErrorField;
            }
            set {
                this.orderErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class StatusRequest {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string signatureField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class RebillResult {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string statusCodeField;
        
        private string transactionErrorField;
        
        private string transactionStatusField;
        
        private string transactionTypeField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionError {
            get {
                return this.transactionErrorField;
            }
            set {
                this.transactionErrorField = value;
            }
        }
        
        /// <remarks/>
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class RebillRequest {
        
        private string merchantIDField;
        
        private string orderAmountField;
        
        private string orderDescriptionField;
        
        private string orderReferenceField;
        
        private string originalOrderReferenceField;
        
        private string recurringTokenField;
        
        private string signatureField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderAmount {
            get {
                return this.orderAmountField;
            }
            set {
                this.orderAmountField = value;
            }
        }
        
        /// <remarks/>
        public string orderDescription {
            get {
                return this.orderDescriptionField;
            }
            set {
                this.orderDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string originalOrderReference {
            get {
                return this.originalOrderReferenceField;
            }
            set {
                this.originalOrderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string recurringToken {
            get {
                return this.recurringTokenField;
            }
            set {
                this.recurringTokenField = value;
            }
        }
        
        /// <remarks/>
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class CancelResult {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string statusCodeField;
        
        private string transactionStatusField;
        
        private string transactionTypeField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class CancelRequest {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string amountField;
        
        private string signatureField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class CaptureResult {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string statusCodeField;
        
        private string transactionStatusField;
        
        private string transactionTypeField;
        
        private string transactionErrorField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionError {
            get {
                return this.transactionErrorField;
            }
            set {
                this.transactionErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class CaptureRequest {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string amountField;
        
        private string signatureField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:PtCard")]
    public partial class SaleResult {
        
        private string merchantIDField;
        
        private string orderReferenceField;
        
        private string recurringTokenField;
        
        private string statusCodeField;
        
        private string transactionErrorField;
        
        private string transactionStatusField;
        
        private string transactionTypeField;
        
        private string verificationParamsField;
        
        private string verificationUrlField;
        
        /// <remarks/>
        public string merchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string orderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string recurringToken {
            get {
                return this.recurringTokenField;
            }
            set {
                this.recurringTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionError {
            get {
                return this.transactionErrorField;
            }
            set {
                this.transactionErrorField = value;
            }
        }
        
        /// <remarks/>
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string verificationParams {
            get {
                return this.verificationParamsField;
            }
            set {
                this.verificationParamsField = value;
            }
        }
        
        /// <remarks/>
        public string verificationUrl {
            get {
                return this.verificationUrlField;
            }
            set {
                this.verificationUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void authCompletedEventHandler(object sender, authCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaleResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaleResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void saleCompletedEventHandler(object sender, saleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaleResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaleResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void captureCompletedEventHandler(object sender, captureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class captureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal captureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CaptureResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CaptureResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void cancelCompletedEventHandler(object sender, cancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void authRebillCompletedEventHandler(object sender, authRebillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authRebillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authRebillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RebillResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RebillResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void rebillCompletedEventHandler(object sender, rebillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rebillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rebillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RebillResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RebillResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void statusCompletedEventHandler(object sender, statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void scheduleCompletedEventHandler(object sender, scheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class scheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal scheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ScheduleResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ScheduleResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void descheduleCompletedEventHandler(object sender, descheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class descheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal descheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DescheduleResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DescheduleResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591